"""Initial migration

Revision ID: b853233ac3d0
Revises: 612b3cb3a9bb
Create Date: 2024-08-07 19:34:55.400780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b853233ac3d0'
down_revision = '612b3cb3a9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
