"""Initial migration

Revision ID: e4d40cd1b582
Revises: 2b28a2195782
Create Date: 2024-08-07 19:57:57.139490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d40cd1b582'
down_revision = '2b28a2195782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
