"""Initial migration

Revision ID: fb196ad7d562
Revises: b853233ac3d0
Create Date: 2024-08-07 19:39:33.650846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb196ad7d562'
down_revision = 'b853233ac3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
